#! /bin/sh

DIR=$(dirname "$0")
source ${DIR}/config

sxhkd 2> /dev/null &

# bspc monitor -d i ii iii iv vi vii
bspc monitor -d "一" "二" "三" "四" "五" "六" "七" "八" "九" "十"

# bspwm config
# -----------------------------------------------

bspc config border_width            3
bspc config window_gap              10

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config presel_feedback_color   ${BG}

bspc config top_padding 25
bspc config bottom_padding 25


# Border Colors
# -----------------------------------------------

bspc config focused_border_color        "#c9c925"
bspc config active_border_color         "#5c5dad"
bspc config normal_border_color         "#222222"

# Rules
# -----------------------------------------------

bspc rule -a Firefox desktop=^2  floating=true
bspc rule -a Geany desktop=^3
bspc rule -a Thunar desktop=^4 
bspc rule -a Gimp desktop=^5  floating=true

# panel
# -----------------------------------------------

# source ${DIR}/panel &
$HOME/.config/polybar/launch.sh &

# autostart
# -----------------------------------------------

xsetroot -solid "#333333" &
compton &
nitrogen --restore &
# nm-applet &
dunst 2> /dev/null &
# parcellite &

# xfce4-terminal &
# xfce4-terminal &
# firefox &
# sh -c 'sleep 10; exec geany' &
# sh -c 'sleep 15; exec thunar' &


