#!/bin/bash
# ------------------------------------------------------------------
#
#     Scripts/netinfo
#     Description: Script for piping the current ESSID through dzen
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

# 'iwconfig wlan0' is deprecated, use 'iw dev wlan0 info'

# Debian user may use this option to enable iwconfig for no root user
# chmod u+s /sbin/iwconfig, which lead to security issue or
# set /etc/sudoers.d for iw

if [[ $(cat /sys/class/net/enp0s4/carrier) = 1 ]]; then
    ICON="net_wired.xbm"
    ESSID="( wired )"
else
    ESSID=$(/sbin/iwconfig wlan0 |  awk -F '"' 'NR==1 {print $2}')
    ICON="wireless.xbm"
    if [[ $ESSID = "" ]]; then
        ICON=""
    fi
fi

ICON='^i(/home/epsi/.xmonad/assets/monitor/'"$ICON)"
echo "$ICON  $ESSID"
